# --------------------------------
# GeyserConnect Configuration File
# --------------------------------

# The IP address that will listen for connections
address: 0.0.0.0

# The IP address remote clients use to connect, can be set to 'auto' to fetch from the web
remote-address: auto

# The port that will listen for connections
port: 19132

# If debug messages should be sent through console
debug-mode: false

# Maximum amount of players that can connect
max-players: 100

# MOTD to display
motd: "GeyserConnect Proxy"

# Welcome message file, if file exists and is not empty this will show on join
# This is loaded live so will update without a server restart
welcome-file: welcome.txt

# Config for the Geyser listener
geyser:
  # The port that will listen for connections
  port: 19133

  # Configures if chunk caching should be enabled or not.
  cache-chunks: true

  # If password authentication should be allowed in online mode.
  allow-password-authentication: false

  # If debug messages should be sent through console, has to be enabled in both places to work
  debug-mode: false

  # The time to wait after the last player disconnects to shutdown the proxy
  # In seconds, set to -1 to disable
  shutdown-time: 300

# A global list of servers sent to all clients
servers:
  - address: test.geysermc.org
    port: 19132
    bedrock: true
    name: Official Geyser Test Server
    imageUrl: https://geysermc.org/android-chrome-192x192.png
  - address: "play.cubecraft.net"
  - address: "127.0.0.1"
    port: 25565

custom-servers:
  # Should custom servers be enabled for users
  enabled: false

  # Max amount of custom servers per user
  max: 10

  # Storage engine for custom servers
  # Can be json, sqlite, mysql
  storage-type: json

  # Connection details for the mysql storage type
  mysql:
    user: "geyser_connect"
    pass: ""
    database: "geyser_connect"
    host: "localhost"
    port: 3306

