# --------------------------------
# GeyserConnect Configuration File
# --------------------------------

# Welcome message file, if file exists and is not empty this will show on join
# This is loaded live so will update without a server restart
welcome-file: welcome.txt

# A global list of servers sent to all clients
servers:
  - name: The Hive
    address: 167.114.81.89
    port: 19132
    bedrock: true
    category: OFFICIAL
    imageUrl: 'https://i.imgur.com/myXmr7B.png'

  - name: CubeCraft
    address: 94.23.159.81
    port: 19132
    bedrock: true
    category: OFFICIAL
    imageUrl: 'https://i.imgur.com/f83ZeDS.jpg'

  - name: Galaxite
    address: 54.39.243.199
    port: 19132
    bedrock: true
    category: OFFICIAL
    imageUrl: 'https://i.imgur.com/PEkLROT.jpg'

  - name: Lifeboat Network
    address: 63.143.54.198
    port: 19132
    bedrock: true
    category: OFFICIAL
    imageUrl: 'https://i.imgur.com/GjsxhCI.png'

  - name: Mineplex
    address: 108.178.12.38
    port: 19132
    bedrock: true
    category: OFFICIAL
    imageUrl: 'https://i.imgur.com/xB6yncS.png'

  - name: MineVille
    address: 52.234.130.255
    port: 19132
    bedrock: true
    category: OFFICIAL
    imageUrl: 'https://i.imgur.com/yqrfMhP.jpg'

  - name: Pixel Paradise
    address: 40.87.84.59
    port: 19132
    bedrock: true
    category: OFFICIAL
    imageUrl: 'https://i.imgur.com/fXQdou8.jpg'

  - name: Official Geyser Test Server
    address: test.geysermc.org
    port: 19132
    bedrock: true
    category: GEYSER
    imageUrl: 'https://geysermc.org/android-chrome-192x192.png'

custom-servers:
  # Should custom servers be enabled for users
  enabled: false

  # Max amount of custom servers per user
  max: 10

  # Storage engine for custom servers
  # Can be json, sqlite, mysql
  storage-type: json

  # Connection details for the mysql storage type
  mysql:
    user: "geyser_connect"
    pass: ""
    database: "geyser_connect"
    host: "localhost"
    port: 3306

# Enable virtual hosts to be specified to skip the server list
# Allows people to connect using addresses like
#   hypixel.net._p25565.example.com
#   hypixel.net.example.com
#   hypixel.net._o.example.com    - For offline mode
vhost:
  # Should this be enabled
  enabled: false

  # The base domain pointing to the server
  base-domain: example.com
